NOISSUE add Install Quilt button
MultiMC/Launcher pull request #3760
Opened 2021-05-03 18:50 UTC by kb-1000

Draft as Quilt is not actually "released" yet.
Requires MultiMC/meta#4.

2021-05-03 18:59 UTC, ImperatorStorm requested changes

2021-05-03 18:59 UTC, ImperatorStorm commented on application/pages/instance/VersionPage.cpp
> +    vselect.setEmptyErrorString(tr("Couldn't load or download the Fabric Loader version lists!"));
shouldn't this be "Quilt Loader"?

2021-05-03 19:29 UTC, kb-1000 commented on application/pages/instance/VersionPage.cpp
> +    vselect.setEmptyErrorString(tr("Couldn't load or download the Fabric Loader version lists!"));
Yes it should, fixed

2021-07-22 16:25 UTC, peterix commented
Hm. This is a bit premature and pretty small compared to the changes needed in meta and elsewhere.

2021-07-22 17:06 UTC, kb-1000 commented
> This is a bit premature

There's a reason why this was marked as a draft PR.

2022-04-20 16:23 UTC, glowiak commented
We are four parallel universes ahead of you

2022-04-23 16:34 UTC, merged