NOISSUE Enforce allowed domains in Modrinth packs
MultiMC/Launcher pull request #4733
Opened 2022-05-28 19:25 UTC by arthomnix

Adds a check to make sure that download URLs in Modrinth packs are on an allowed domain as per the [Modrinth pack specification](https://docs.modrinth.com/docs/modpacks/format_definition/#downloads).

This will likely break a lot of current Modrinth packs as it does not include CurseForge CDN domains that were recently removed from the specification upon CurseForge's request. It may be advisable to delay merging until Modrinth has removed packs with CF download URLs from their website.

2022-05-28 19:32 UTC, peterix requested changes

2022-05-28 19:32 UTC, peterix commented on launcher/modplatform/modrinth/ModrinthPackManifest.h
> +const QString allowedDownloadDomains[] = {
Use `QStringList` instead.

2022-05-28 19:32 UTC, peterix commented on launcher/InstanceImportTask.cpp
> +                if (std::find(std::begin(Modrinth::allowedDownloadDomains), std::end(Modrinth::allowedDownloadDomains), downloadDomain) == std::end(Modrinth::allowedDownloadDomains))
Use https://doc.qt.io/qt-5/qstringlist.html#contains instead of this magic.

2022-05-29 16:08 UTC, arthomnix commented
Closing as Modrinth have clarified that the domain restrictions are specific to their platform rather than the pack format as a whole

2022-05-29 16:08 UTC, closed without merging