NOISSUE Fix shortcut dialog bugs
MultiMC/Launcher pull request #5162
Opened 2023-05-22 16:36 UTC by arthomnix

Fixes bugs in the create shortcut dialog where the OK button and server address text box were always disabled on instances that don't support Quick Play.

2023-05-22 23:18 UTC, peterix requested changes

2023-05-22 23:18 UTC, peterix commented on launcher/ui/dialogs/CreateShortcutDialog.ui
> +  </connection>
Please do not add more of these, connect the signals directly in code

2023-05-22 23:20 UTC, peterix commented on launcher/ui/dialogs/CreateShortcutDialog.ui
> +  </connection>
And ideally using the new style syntax, like here:
![image](https://github.com/MultiMC/Launcher/assets/203326/30f6df54-ed13-47f7-bf35-0cd833812c57)

2023-05-23 20:09 UTC, arthomnix commented
(accidentally committed changes intended for #5163 to the wrong branch)

2023-05-24 08:02 UTC, merged